### ISSUE TITLE
Error adding entities for domain fan with platform hwam_stove

### ISSUE THREAD

**Issue by Schrikt** [mvn23/hwam_stove#5]
```Logger: homeassistant.components.fan
Source: components/fan/__init__.py:565
Integration: Fan (documentation, issues)
First occurred: 2:19:20 PM (2 occurrences)
Last logged: 2:19:21 PM

Error adding entities for domain fan with platform hwam_stove
Error while setting up hwam_stove platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 620, in state_attributes
    data[ATTR_PERCENTAGE] = self.percentage
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 481, in percentage
    return self.speed_to_percentage(self.speed)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 565, in speed_to_percentage
    raise NotValidSpeedError(f"The speed {speed} is not a valid speed.")
homeassistant.components.fan.NotValidSpeedError: The speed None is not a valid speed.
```

**Comment by mvn23** [comment]
Does #6 fix the issue? (Again, untested code...)

**Comment by tofrie** [comment]
Works fine with core-2021.8.8. No more problems…
